FROM alpine:3

LABEL author="Sahat Matua SInaga"
LABEL company="Institut Teknologi Kalimantan" Website="https://github.com/sahat1406/praktikum-docker"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"